-- Tiny Tank Maze global leaderboard
-- Run this entire file once in the Supabase SQL Editor.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  mode text not null,
  score integer not null default 0,
  wave integer not null default 1,
  kills integer not null default 0,
  cleared boolean not null default false,
  created_at timestamptz not null default now(),

  constraint leaderboard_player_name_length
    check (char_length(trim(player_name)) between 1 and 16),

  constraint leaderboard_mode_valid
    check (mode in ('classic', 'infinite')),

  constraint leaderboard_score_range
    check (score between 0 and 100000000),

  constraint leaderboard_wave_range
    check (wave between 1 and 100000),

  constraint leaderboard_kills_range
    check (kills between 0 and 1000000)
);

create index if not exists leaderboard_classic_rank_idx
  on public.leaderboard (mode, score desc, created_at asc);

create index if not exists leaderboard_infinite_rank_idx
  on public.leaderboard (mode, wave desc, score desc, created_at asc);

alter table public.leaderboard enable row level security;

revoke all on table public.leaderboard from anon, authenticated;
grant select on table public.leaderboard to anon, authenticated;

drop policy if exists "Public can read leaderboard" on public.leaderboard;
create policy "Public can read leaderboard"
  on public.leaderboard
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can submit leaderboard scores" on public.leaderboard;
-- INSERT uses the server's secret/service_role key after run validation.
-- Intentionally no INSERT, UPDATE or DELETE grants/policies for browser users.
